name: SafetyNet
description: "v1"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  cupertino_icons: ^1.0.6


+de++v_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/