name: SafetyNet
description: "v1"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
#  sensors_plus: ^3.0.4
#  geolocator: ^10.1.0
#  flutter_compass: ^0.8.0
#  flutter_background_service: ^2.2.0
#  flutter_local_notifications: ^13.0.0
#  permission_handler: ^10.0.0
#  device_info_plus: ^9.0.0
#  rxdart: ^0.27.0
#  audioplayers: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emergency_alert.wav
    - config.env