name: safety_net
description: A safety monitoring application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.0
  sensors_plus: ^4.0.1
  rxdart: ^0.27.7
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  http: ^1.1.0
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.2
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/